/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        gestionoc: {
          "primary":           "#2a7a2e",
          "primary-content":   "#ffffff",
          "secondary":         "#4db520",
          "secondary-content": "#ffffff",
          "accent":            "#f5921d",
          "accent-content":    "#ffffff",
          "neutral":           "#374151",
          "neutral-content":   "#f9fafb",
          "base-100":          "#ffffff",
          "base-200":          "#f4fbe8",
          "base-300":          "#e4f2cc",
          "base-content":      "#1a2e1a",
          "info":              "#3b82f6",
          "success":           "#22c55e",
          "warning":           "#eab308",
          "error":             "#ef4444",
        },
      },
      {
        "gestionoc-dark": {
          "primary":           "#52c822",
          "primary-content":   "#071a07",
          "secondary":         "#2a7a2e",
          "secondary-content": "#ffffff",
          "accent":            "#f5921d",
          "accent-content":    "#1a0a00",
          "neutral":           "#1e2c1e",
          "neutral-content":   "#d0ecd0",
          "base-100":          "#1a261a",
          "base-200":          "#142014",
          "base-300":          "#253225",
          "base-content":      "#d0ecd0",
          "info":              "#60a5fa",
          "success":           "#4ade80",
          "warning":           "#fbbf24",
          "error":             "#f87171",
        },
      },
    ],
    darkTheme: "gestionoc-dark",
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
}
